export type ApiRegistryEntry = {
  name: string;
  method: string;
  path: string;
  description: string;
  mobile_ready: boolean;
};

const resourceNames = [
  "users",
  "clubs",
  "organizations",
  "dashboards",
  "organization_users",
  "athletes",
  "simplified_athletes",
  "medical_certificates",
  "simplified_certificates",
  "payments",
  "simplified_payments",
  "payment_methods",
  "invoices",
  "receipts",
  "trainer_payments",
  "notifications",
  "simplified_notifications",
  "training_attendance",
  "assets",
  "access_tokens",
  "appointments",
  "bank_accounts",
  "categories",
  "clothing_inventory",
  "clothing_kits",
  "clothing_products",
  "discounts",
  "document_templates",
  "expected_expenses",
  "expected_income",
  "jersey_assignments",
  "jersey_groups",
  "kit_assignments",
  "matches",
  "members",
  "opening_hours",
  "payment_plans",
  "procure",
  "secretariat_notes",
  "sponsor_payments",
  "sponsors",
  "staff_members",
  "trainers",
  "trainings",
  "transactions",
  "transfers",
  "weekly_schedule",
];

export const API_REGISTRY: ApiRegistryEntry[] = [
  {
    name: "registry.list",
    method: "GET",
    path: "/api/v1/registry",
    description: "Registro completo API per web e mobile",
    mobile_ready: true,
  },
  {
    name: "auth.login",
    method: "POST",
    path: "/api/v1/auth/login",
    description: "Login utente e apertura sessione",
    mobile_ready: true,
  },
  {
    name: "auth.register",
    method: "POST",
    path: "/api/v1/auth/register",
    description: "Registrazione utente con verifica account",
    mobile_ready: true,
  },
  {
    name: "auth.logout",
    method: "POST",
    path: "/api/v1/auth/logout",
    description: "Logout e chiusura sessione",
    mobile_ready: true,
  },
  {
    name: "auth.session",
    method: "GET",
    path: "/api/v1/auth/session",
    description: "Sessione corrente",
    mobile_ready: true,
  },
  {
    name: "auth.user",
    method: "GET|PATCH",
    path: "/api/v1/auth/user",
    description: "Profilo utente autenticato",
    mobile_ready: true,
  },
  {
    name: "auth.memberships",
    method: "GET",
    path: "/api/v1/auth/memberships",
    description: "Elenco club dell'account con ruoli e proprieta",
    mobile_ready: true,
  },
  {
    name: "auth.memberships.activate",
    method: "POST",
    path: "/api/v1/auth/memberships/activate",
    description: "Imposta il club attivo dell'account",
    mobile_ready: true,
  },
  {
    name: "auth.access.redeem",
    method: "POST",
    path: "/api/v1/auth/access/redeem",
    description: "Collega l'account a un club tramite token condiviso",
    mobile_ready: true,
  },
  {
    name: "auth.providers",
    method: "GET",
    path: "/api/v1/auth/providers",
    description: "Provider auth esterni disponibili",
    mobile_ready: true,
  },
  {
    name: "auth.verify.email.send",
    method: "POST",
    path: "/api/v1/auth/verify/email/send",
    description: "Invio codice verifica email",
    mobile_ready: true,
  },
  {
    name: "auth.verify.email.confirm",
    method: "POST",
    path: "/api/v1/auth/verify/email/confirm",
    description: "Conferma verifica email e finalizzazione sessione",
    mobile_ready: true,
  },
  {
    name: "auth.verify.phone.send",
    method: "POST",
    path: "/api/v1/auth/verify/phone/send",
    description: "Invio codice verifica telefono",
    mobile_ready: true,
  },
  {
    name: "auth.verify.phone.confirm",
    method: "POST",
    path: "/api/v1/auth/verify/phone/confirm",
    description: "Conferma verifica telefono e finalizzazione sessione",
    mobile_ready: true,
  },
  {
    name: "auth.oauth.start",
    method: "GET",
    path: "/api/v1/auth/oauth/:provider/start",
    description: "Avvio login OAuth web",
    mobile_ready: false,
  },
  {
    name: "auth.oauth.callback",
    method: "GET",
    path: "/api/v1/auth/oauth/:provider/callback",
    description: "Callback OAuth web",
    mobile_ready: false,
  },
  ...resourceNames.flatMap((resource) => [
    {
      name: `${resource}.list`,
      method: "GET",
      path: `/api/v1/${resource}`,
      description: `Lista risorsa ${resource}`,
      mobile_ready: true,
    },
    {
      name: `${resource}.create`,
      method: "POST",
      path: `/api/v1/${resource}`,
      description: `Creazione risorsa ${resource}`,
      mobile_ready: true,
    },
    {
      name: `${resource}.detail`,
      method: "GET",
      path: `/api/v1/${resource}/:id`,
      description: `Dettaglio risorsa ${resource}`,
      mobile_ready: true,
    },
    {
      name: `${resource}.update`,
      method: "PATCH",
      path: `/api/v1/${resource}/:id`,
      description: `Aggiornamento risorsa ${resource}`,
      mobile_ready: true,
    },
    {
      name: `${resource}.delete`,
      method: "DELETE",
      path: `/api/v1/${resource}/:id`,
      description: `Eliminazione risorsa ${resource}`,
      mobile_ready: true,
    },
  ]),
];
