export type ApiRegistryEntry = {
  name: string;
  method: string;
  path: string;
  description: string;
  mobile_ready: boolean;
};

const resourceNames = [
  "users",
  "clubs",
  "organizations",
  "dashboards",
  "organization_users",
  "club_resource_items",
  "athletes",
  "athlete_category_memberships",
  "simplified_athletes",
  "medical_certificates",
  "simplified_certificates",
  "payments",
  "simplified_payments",
  "payment_methods",
  "invoices",
  "receipts",
  "trainer_payments",
  "notifications",
  "simplified_notifications",
  "training_attendance",
  "assets",
  "access_tokens",
  "appointments",
  "bank_accounts",
  "categories",
  "category_groups",
  "clothing_inventory",
  "clothing_kits",
  "clothing_products",
  "club_sites",
  "discounts",
  "document_templates",
  "expected_expenses",
  "expected_income",
  "jersey_assignments",
  "jersey_groups",
  "kit_assignments",
  "matches",
  "members",
  "opening_hours",
  "payment_plans",
  "procure",
  "secretariat_notes",
  "sponsor_payments",
  "sponsors",
  "staff_members",
  "trainers",
  "trainings",
  "transactions",
  "transfers",
  "weekly_schedule",
];

export const API_REGISTRY: ApiRegistryEntry[] = [
  {
    name: "registry.list",
    method: "GET",
    path: "/api/v1/registry",
    description: "Registro completo API per web e mobile",
    mobile_ready: true,
  },
  {
    name: "comuni.search",
    method: "GET",
    path: "/api/v1/comuni",
    description:
      "Archivio ISTAT dei comuni italiani: ricerca per nome, per codice catastale o per omonimia",
    mobile_ready: true,
  },
  {
    name: "athletes.avatar",
    method: "GET",
    path: "/api/v1/athletes/:id/avatar",
    description:
      "La foto di un atleta come immagine: la lista riceve un indirizzo, non un base64",
    mobile_ready: true,
  },
  {
    name: "attachments.list",
    method: "GET",
    path: "/api/v1/attachments",
    description:
      "Metadati degli allegati di una risorsa del club. Mai i byte",
    mobile_ready: true,
  },
  {
    name: "attachments.upload",
    method: "POST",
    path: "/api/v1/attachments",
    description: "Caricamento di un allegato (multipart/form-data)",
    mobile_ready: true,
  },
  {
    name: "attachments.file",
    method: "GET|PUT|DELETE",
    path: "/api/v1/attachments/:id",
    description:
      "Contenuto di un allegato: visualizzazione, download, sostituzione, eliminazione",
    mobile_ready: true,
  },
  {
    name: "payment_transactions.list",
    method: "GET",
    path: "/api/v1/payment-transactions",
    description:
      "Registro incassi: i movimenti di denaro di un club, di un atleta o di una rata",
    mobile_ready: true,
  },
  {
    name: "payment_transactions.create",
    method: "POST",
    path: "/api/v1/payment-transactions",
    description:
      "Registra un incasso su una rata e ne ricalcola lo stato nella stessa transazione",
    mobile_ready: true,
  },
  {
    name: "payment_transactions.actions",
    method: "POST",
    path: "/api/v1/payment-transactions/:id",
    description:
      "Azioni su un incasso: `reverse` lo storna senza cancellarlo, `issue-receipt` ne emette la ricevuta, `issue-invoice` la fattura",
    mobile_ready: true,
  },
  {
    name: "funding.reconciliation",
    method: "GET",
    path: "/api/v1/funding/programs/:id/reconciliation",
    description:
      "Riconciliazione di un bando: una riga per atleta e periodo, con la misura grezza accanto al requisito. `?format=csv` la scarica",
    mobile_ready: false,
  },
  {
    name: "documents.printable",
    method: "GET",
    path: "/api/v1/documents/:kind/:id",
    description:
      "Il documento stampabile di una ricevuta o di una fattura, con il branding della societa. Restituisce HTML",
    mobile_ready: false,
  },
  {
    name: "entitlements.read",
    method: "GET",
    path: "/api/v1/entitlements",
    description:
      "Cosa un club puo usare: esito e motivo funzione per funzione, calcolati su piano, servizi attivi ed eccezioni",
    mobile_ready: false,
  },
  {
    name: "entitlements.override",
    method: "POST",
    path: "/api/v1/entitlements",
    description:
      "Concede o revoca una funzione a un club. Solo platform_admin: e una decisione di Cedi verso un cliente",
    mobile_ready: false,
  },
  {
    name: "funding.programs",
    method: "GET|POST",
    path: "/api/v1/funding/programs",
    description:
      "Programmi di contributo: le regole di un bando sono configurazione, non codice",
    mobile_ready: false,
  },
  {
    name: "funding.programs.detail",
    method: "GET|PATCH",
    path: "/api/v1/funding/programs/:id",
    description:
      "Dettaglio e modifica di un programma. Nessun DELETE: un programma con maturati si chiude",
    mobile_ready: false,
  },
  {
    name: "funding.enrollments",
    method: "GET|POST",
    path: "/api/v1/funding/enrollments",
    description:
      "Beneficiari di un contributo. `view=overview` restituisce i cinque importi gia calcolati",
    mobile_ready: false,
  },
  {
    name: "funding.accruals",
    method: "GET|POST",
    path: "/api/v1/funding/accruals",
    description:
      "Maturato per periodo: `recompute` lo ricalcola dalle presenze, `report` lo rendiconta all'ente",
    mobile_ready: false,
  },
  {
    name: "funding.settlements",
    method: "GET|POST",
    path: "/api/v1/funding/settlements",
    description:
      "Liquidazioni dell'ente, riconciliate con i periodi maturati di ciascun atleta",
    mobile_ready: false,
  },
  {
    name: "forms.list",
    method: "GET|POST",
    path: "/api/v1/forms",
    description:
      "Moduli del club: elenco e creazione da un modello di partenza",
    mobile_ready: false,
  },
  {
    name: "forms.detail",
    method: "GET|PATCH|DELETE",
    path: "/api/v1/forms/:id",
    description:
      "Un modulo: bozza, pubblicazione, archiviazione, duplicazione, link pubblico",
    mobile_ready: false,
  },
  {
    name: "forms.submissions",
    method: "GET|POST",
    path: "/api/v1/forms/submissions",
    description:
      "Coda delle compilazioni da esaminare e compilazione dalla segreteria",
    mobile_ready: false,
  },
  {
    name: "forms.submission",
    method: "GET|POST",
    path: "/api/v1/forms/submissions/:id",
    description:
      "Una compilazione: cosa cambierebbe approvandola, possibili duplicati, approvazione o rifiuto",
    mobile_ready: false,
  },
  {
    name: "auth.login",
    method: "POST",
    path: "/api/v1/auth/login",
    description: "Login utente e apertura sessione",
    mobile_ready: true,
  },
  {
    name: "auth.register",
    method: "POST",
    path: "/api/v1/auth/register",
    description: "Registrazione utente con verifica account",
    mobile_ready: true,
  },
  {
    name: "auth.logout",
    method: "POST",
    path: "/api/v1/auth/logout",
    description: "Logout e chiusura sessione",
    mobile_ready: true,
  },
  {
    name: "auth.session",
    method: "GET",
    path: "/api/v1/auth/session",
    description: "Sessione corrente",
    mobile_ready: true,
  },
  {
    name: "auth.user",
    method: "GET|PATCH",
    path: "/api/v1/auth/user",
    description: "Profilo utente autenticato",
    mobile_ready: true,
  },
  {
    name: "auth.memberships",
    method: "GET",
    path: "/api/v1/auth/memberships",
    description: "Elenco club dell'account con ruoli e proprieta",
    mobile_ready: true,
  },
  {
    name: "auth.memberships.activate",
    method: "POST",
    path: "/api/v1/auth/memberships/activate",
    description: "Imposta il club attivo dell'account",
    mobile_ready: true,
  },
  {
    name: "auth.access.redeem",
    method: "POST",
    path: "/api/v1/auth/access/redeem",
    description: "Collega l'account a un club tramite token condiviso",
    mobile_ready: true,
  },
  {
    name: "auth.providers",
    method: "GET",
    path: "/api/v1/auth/providers",
    description: "Provider auth esterni disponibili",
    mobile_ready: true,
  },
  {
    name: "auth.verify.email.send",
    method: "POST",
    path: "/api/v1/auth/verify/email/send",
    description: "Invio codice verifica email",
    mobile_ready: true,
  },
  {
    name: "auth.verify.email.confirm",
    method: "POST",
    path: "/api/v1/auth/verify/email/confirm",
    description: "Conferma verifica email e finalizzazione sessione",
    mobile_ready: true,
  },
  {
    name: "auth.verify.phone.send",
    method: "POST",
    path: "/api/v1/auth/verify/phone/send",
    description: "Invio codice verifica telefono",
    mobile_ready: true,
  },
  {
    name: "auth.verify.phone.confirm",
    method: "POST",
    path: "/api/v1/auth/verify/phone/confirm",
    description: "Conferma verifica telefono e finalizzazione sessione",
    mobile_ready: true,
  },
  {
    name: "auth.password.forgot",
    method: "POST",
    path: "/api/v1/auth/password/forgot",
    description:
      "Richiesta reset password: invia via SMTP un link monouso valido 30 minuti",
    mobile_ready: true,
  },
  {
    name: "auth.password.reset",
    method: "POST",
    path: "/api/v1/auth/password/reset",
    description:
      "Imposta la nuova password dal token di reset e revoca tutte le sessioni",
    mobile_ready: true,
  },
  {
    name: "auth.oauth.start",
    method: "GET",
    path: "/api/v1/auth/oauth/:provider/start",
    description: "Avvio login OAuth web",
    mobile_ready: false,
  },
  {
    name: "auth.oauth.callback",
    method: "GET",
    path: "/api/v1/auth/oauth/:provider/callback",
    description: "Callback OAuth web",
    mobile_ready: false,
  },
  {
    name: "admin.overview",
    method: "GET",
    path: "/api/v1/admin/overview",
    description: "Panoramica di piattaforma: account, club e accessi",
    mobile_ready: false,
  },
  {
    name: "admin.email.get",
    method: "GET",
    path: "/api/v1/admin/email",
    description: "Configurazione SMTP di piattaforma, senza la password",
    mobile_ready: false,
  },
  {
    name: "admin.email.save",
    method: "PUT",
    path: "/api/v1/admin/email",
    description: "Salvataggio configurazione SMTP, password cifrata a riposo",
    mobile_ready: false,
  },
  {
    name: "admin.email.test",
    method: "POST",
    path: "/api/v1/admin/email/test",
    description: "Invio di una email di prova con la configurazione salvata",
    mobile_ready: false,
  },
  {
    name: "admin.imap.get",
    method: "GET",
    path: "/api/v1/admin/imap",
    description: "Configurazione IMAP di piattaforma, senza la password",
    mobile_ready: false,
  },
  {
    name: "admin.imap.save",
    method: "PUT",
    path: "/api/v1/admin/imap",
    description: "Salvataggio configurazione IMAP, password cifrata a riposo",
    mobile_ready: false,
  },
  {
    name: "admin.imap.test",
    method: "POST",
    path: "/api/v1/admin/imap/test",
    description: "Prova di connessione e autenticazione sulla casella IMAP",
    mobile_ready: false,
  },
  {
    name: "seasons.list",
    method: "GET",
    path: "/api/v1/seasons",
    description:
      "Stagioni del club attivo, con quante voci riportabili contiene ciascuna",
    mobile_ready: false,
  },
  {
    name: "seasons.create",
    method: "POST",
    path: "/api/v1/seasons",
    description:
      "Creazione stagione, con l'eventuale riporto dalla stagione scelta",
    mobile_ready: false,
  },
  {
    name: "seasons.status",
    method: "PATCH",
    path: "/api/v1/seasons/:seasonId",
    description: "Attivazione o archiviazione di una stagione",
    mobile_ready: false,
  },
  {
    name: "seasons.rollover",
    method: "POST",
    path: "/api/v1/seasons/:seasonId/rollover",
    description:
      "Riporto della configurazione verso la stagione indicata; `preview` calcola senza scrivere",
    mobile_ready: false,
  },
  ...resourceNames.flatMap((resource) => [
    {
      name: `${resource}.list`,
      method: "GET",
      path: `/api/v1/${resource}`,
      description: `Lista risorsa ${resource}`,
      mobile_ready: true,
    },
    {
      name: `${resource}.create`,
      method: "POST",
      path: `/api/v1/${resource}`,
      description: `Creazione risorsa ${resource}`,
      mobile_ready: true,
    },
    {
      name: `${resource}.detail`,
      method: "GET",
      path: `/api/v1/${resource}/:id`,
      description: `Dettaglio risorsa ${resource}`,
      mobile_ready: true,
    },
    {
      name: `${resource}.update`,
      method: "PATCH",
      path: `/api/v1/${resource}/:id`,
      description: `Aggiornamento risorsa ${resource}`,
      mobile_ready: true,
    },
    {
      name: `${resource}.delete`,
      method: "DELETE",
      path: `/api/v1/${resource}/:id`,
      description: `Eliminazione risorsa ${resource}`,
      mobile_ready: true,
    },
  ]),
];
